FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MailDesk.API.csproj", "./"]
RUN dotnet restore "MailDesk.API.csproj"
COPY . .
RUN dotnet build "MailDesk.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MailDesk.API.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "MailDesk.API.dll"]