// <auto-generated />
using System;
using MailDesk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailDesk.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511063008_AddDitujukanKeIdToSurat")]
    partial class AddDitujukanKeIdToSurat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailDesk.API.Entities.Disposisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Instruksi")
                        .HasColumnType("text")
                        .HasColumnName("instruksi");

                    b.Property<string>("JenisAksi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PemberiId")
                        .HasColumnType("integer")
                        .HasColumnName("pemberi_id");

                    b.Property<int>("PenerimaId")
                        .HasColumnType("integer")
                        .HasColumnName("penerima_id");

                    b.Property<string>("SifatDisposisi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sifat_disposisi");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("SuratId")
                        .HasColumnType("integer")
                        .HasColumnName("surat_id");

                    b.Property<DateOnly>("TanggalDisposisi")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_disposisi");

                    b.Property<DateTime?>("WaktuDiterima")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("waktu_diterima");

                    b.HasKey("Id");

                    b.HasIndex("PemberiId");

                    b.HasIndex("PenerimaId");

                    b.HasIndex("SuratId");

                    b.ToTable("disposisi", t =>
                        {
                            t.HasCheckConstraint("CK_disposisi_sifat", "sifat_disposisi IN ('Biasa', 'Penting', 'Mendesak', 'Rahasia')");

                            t.HasCheckConstraint("CK_disposisi_status", "status IN ('Pending', 'Accepted', 'Completed')");
                        });
                });

            modelBuilder.Entity("MailDesk.API.Entities.DisposisiRelation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("integer")
                        .HasColumnName("child_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("disposisi_relation");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Inbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CatatanPengantar")
                        .HasColumnType("text")
                        .HasColumnName("catatan_pengantar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("PenerimaId")
                        .HasColumnType("integer")
                        .HasColumnName("penerima_id");

                    b.Property<int?>("PengirimId")
                        .HasColumnType("integer")
                        .HasColumnName("pengirim_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("SuratId")
                        .HasColumnType("integer")
                        .HasColumnName("surat_id");

                    b.HasKey("Id");

                    b.HasIndex("PenerimaId");

                    b.HasIndex("PengirimId");

                    b.HasIndex("SuratId");

                    b.ToTable("inbox");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NamaRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nama_role");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Surat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DitujukanKeId")
                        .HasColumnType("integer")
                        .HasColumnName("ditujukan_ke_id");

                    b.Property<byte[]>("FileLampiran")
                        .HasColumnType("bytea")
                        .HasColumnName("file_lampiran");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<string>("IsiTeksOcr")
                        .HasColumnType("text")
                        .HasColumnName("isi_teks_ocr");

                    b.Property<string>("JenisSurat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("jenis_surat");

                    b.Property<string>("KategoriSurat")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kategori_surat");

                    b.Property<string>("NamaFile")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nama_file");

                    b.Property<string>("NoSurat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("no_surat");

                    b.Property<string>("NomorAgenda")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nomor_agenda");

                    b.Property<string>("Penerima")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("penerima");

                    b.Property<string>("Pengirim")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("pengirim");

                    b.Property<string>("Perihal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("perihal");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TanggalSurat")
                        .HasColumnType("date")
                        .HasColumnName("tanggal_surat");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DitujukanKeId");

                    b.HasIndex("NomorAgenda")
                        .IsUnique()
                        .HasFilter("nomor_agenda IS NOT NULL");

                    b.HasIndex("UserId");

                    b.ToTable("surat", t =>
                        {
                            t.HasCheckConstraint("CK_surat_jenis", "jenis_surat IN ('Masuk', 'Keluar')");
                        });
                });

            modelBuilder.Entity("MailDesk.API.Entities.TemplateSurat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DibuatOleh")
                        .HasColumnType("integer")
                        .HasColumnName("dibuat_oleh");

                    b.Property<string>("IsiTemplate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isi_template");

                    b.Property<string>("NamaTemplate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nama_template");

                    b.HasKey("Id");

                    b.HasIndex("DibuatOleh");

                    b.ToTable("template_surat");
                });

            modelBuilder.Entity("MailDesk.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nama");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<int?>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Disposisi", b =>
                {
                    b.HasOne("MailDesk.API.Entities.User", "Pemberi")
                        .WithMany()
                        .HasForeignKey("PemberiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MailDesk.API.Entities.User", "Penerima")
                        .WithMany()
                        .HasForeignKey("PenerimaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MailDesk.API.Entities.Surat", "Surat")
                        .WithMany()
                        .HasForeignKey("SuratId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pemberi");

                    b.Navigation("Penerima");

                    b.Navigation("Surat");
                });

            modelBuilder.Entity("MailDesk.API.Entities.DisposisiRelation", b =>
                {
                    b.HasOne("MailDesk.API.Entities.Disposisi", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MailDesk.API.Entities.Disposisi", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Inbox", b =>
                {
                    b.HasOne("MailDesk.API.Entities.User", "Penerima")
                        .WithMany()
                        .HasForeignKey("PenerimaId");

                    b.HasOne("MailDesk.API.Entities.User", "Pengirim")
                        .WithMany()
                        .HasForeignKey("PengirimId");

                    b.HasOne("MailDesk.API.Entities.Surat", "Surat")
                        .WithMany()
                        .HasForeignKey("SuratId");

                    b.Navigation("Penerima");

                    b.Navigation("Pengirim");

                    b.Navigation("Surat");
                });

            modelBuilder.Entity("MailDesk.API.Entities.Surat", b =>
                {
                    b.HasOne("MailDesk.API.Entities.User", "DitujukanKe")
                        .WithMany()
                        .HasForeignKey("DitujukanKeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MailDesk.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DitujukanKe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailDesk.API.Entities.TemplateSurat", b =>
                {
                    b.HasOne("MailDesk.API.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("DibuatOleh");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MailDesk.API.Entities.User", b =>
                {
                    b.HasOne("MailDesk.API.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
